site_name: Central de Tutoriais AlternaTribe
site_url: https://alternatribe.github.io/

theme:
  name: material
  language: pt-BR
  features:
    - navigation.expand   # Deixa as pastas do menu expansíveis
    - search.suggest      # Ativa sugestões na busca global

plugins:
  - search                # Ativa o sistema de busca em todo o site
