site_name: Central de Tutoriais AlternaTribe
site_url: https://alternatribe.github.io/

theme:
  name: material
  language: pt-BR
  features:
    - navigation.expand   # Deixa as pastas do menu expansíveis
    - search.suggest      # Ativa sugestões na busca global
    - search.highlight    # Destaca os termos buscados na página
    - content.code.copy   # Adiciona um botão de "Copiar" nos blocos de código
    - toc.follow          # Índice direito acompanha a rolagem da página 📌


extra_css:
  - stylesheets/custom.css

copyright: "" 

extra:
    generator: false      # Desativa o link oculto "Feito com MkDocs" nos créditos

plugins:
  - search                # Ativa o sistema de busca em todo o site
  - awesome-pages         # Ativa o organizador automático de menu
  - tags:                 # Ativa sistema de categorias/etiquetas na busca 🏷️
      tags_file: tags.md
  - glightbox             # Efeito de zoom fluido ao clicar nas imagens e prints 🖼️

markdown_extensions:
  - admonition                # Caixas de aviso coloridas (!!! note, !!! danger)
  - attr_list                 # Necessário para o funcionamento do Glightbox
  - pymdownx.details          # Permite criar caixas de aviso retráteis
  - pymdownx.superfences      # Permite colocar códigos dentro das caixas de aviso
  - pymdownx.highlight:       # Coloração automática de código (Codehilite)
      anchor_linenums: true   # Permite linkar linhas específicas de código
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:        # Checkboxes para checklists de tutoriais ▢
      custom_checkbox: true


